name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]   # Desplegar cuando haya un push a la rama 'main'
  workflow_dispatch:      # Permite ejecución manual desde GitHub

permissions:
  contents: read         # Leer el contenido del repositorio
  pages: write           # Permitir escribir en GitHub Pages
  id-token: write        # Permite la generación de tokens

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4

      - name: Install dependencies and build the site
        run: |
          # Primero instala las dependencias en la raíz del monorepo
          npm install  # Cambia a pnpm install o yarn si usas esos gestores

          # Luego ve a la carpeta de Astro para construir el proyecto
          cd packages/docs

          npm run build  # Cambia según tu script de build, si usas otro gestor de paquetes

      - name: Build and upload your site with Astro
        uses: withastro/action@v3
        with:
          path: packages/docs  # Ruta a tu proyecto Astro
          node-version: 20      # Especifica la versión de Node que se usará
          package-manager: npm  # Usa 'pnpm' o 'yarn' si usas otro gestor

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
